name: Run unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Fill config
        uses: DamianReeves/write-file-action@master
        with:
          path: config/config.yaml
          contents: |
            WILL DO IT LATER
          write-mode: overwrite

      - name: Run tests
        run: make test
